---
- name: Install Python3 and pip
  yum:
    name:
      - python3
      - python3-pip
    state: present

- name: Install Flask
  pip:
    name: flask
    executable: pip3

- name: Install SQLite
  yum:
    name: sqlite
    state: present

- name: Create noteapp base directory
  file:
    path: /home/ec2-user/noteapp
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Create subdirectories for the app
  file:
    path: "/home/ec2-user/noteapp/{{ item }}"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'
  loop:
    - app
    - static
    - templates
    - database

- name: Copy app.py to app directory
  copy:
    src: app.py
    dest: /home/ec2-user/noteapp/app/app.py
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Copy index.html to templates directory
  copy:
    src: index.html
    dest: /home/ec2-user/noteapp/templates/index.html
    owner: ec2-user
    group: ec2-user
    mode: '0644'

  
